### ISSUE TITLE
自行编译频繁报错

### ISSUE THREAD

**Issue by Huashusu** [qist/xray-ui#79]
使用CentOS7进行编译，也安装了`glibc-static`，还是无法编译
```shell
[root@CentOS7 xray-ui]# CGO_ENABLED=1 go build -o xray-ui  -ldflags '-linkmode "external" -extldflags "-static"' main.go
# command-line-arguments
/tmp/go-link-1033355033/000017.o：在函数‘unixDlOpen’中：
/root/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.17/sqlite3-binding.c:43784: 警告：Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-1033355033/000004.o：在函数‘_cgo_9c8efe9babca_C2func_getaddrinfo’中：
/tmp/go-build/cgo-gcc-prolog:58: 警告：Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by Huashusu** [comment]
去掉静态库参数再进行编译，能编译过，但是会panic
```shell
[root@CentOS7 xray-ui]# CGO_ENABLED=1 go build -o xray-ui  -ldflags '-linkmode "external"' main.go
[root@CentOS7 xray-ui]# ./xray-ui 
panic: can't disable invalidptr

goroutine 1 [running]:
github.com/sagernet/sing/common/buf.init.0()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.2.5/common/buf/ptr.go:33 +0x85

``` 

是还需要 `cgo` 什么参数吗？还是编译命令问题？

**Comment by qist** [comment]
第一个编译是生成二进制文件的把。那个只是提示如果你不静态编译 `CGO_ENABLED=1 go build -o xui-release -v main.go`  在其它环境兼容不好需要依赖。

**Comment by qist** [comment]
```
/usr/bin/ld: /tmp/go-link-2091103967/000017.o: in function `unixDlOpen':
/root/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.17/sqlite3-binding.c:43784: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2091103967/000004.o: in function `_cgo_cbcce81e6342_C2func_getaddrinfo':
/tmp/go-build/cgo_unix_cgo.cgo2.c:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
属于正常情况
```

**Comment by Huashusu** [comment]
> 第一个编译是生成二进制文件的把。那个只是提示如果你不静态编译 `CGO_ENABLED=1 go build -o xui-release -v main.go` 在其它环境兼容不好需要依赖。

```shell
[root@CentOS7 xray-ui]# CGO_ENABLED=1 go build -o xui-release -v main.go
[root@CentOS7 xray-ui]# ./xui-release 
panic: can't disable invalidptr

goroutine 1 [running]:
github.com/sagernet/sing/common/buf.init.0()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.2.5/common/buf/ptr.go:33 +0x85
```

是我环境有问题吗还是其他什么？

**Comment by qist** [comment]
我还没在centos7 下面编译过。你用的go 版本是多少。`go version go1.20.2`

**Comment by Huashusu** [comment]
> 我还没在centos7 下面编译过。你用的go 版本是多少。`go version go1.20.2`

是`go version go1.21.0 linux/amd64`

**Comment by qist** [comment]
回退到go1.20.x 版本 上游还没支持1.21.0版本。

**Comment by Huashusu** [comment]
> 回退到go1.20.x 版本 上游还没支持1.21.0版本。

谢谢，已经编译成功了

**Comment by qist** [comment]
xray-core 1.8.3 版本依赖版本没更新 你可以修改 go.mod 文件 添加`github.com/sagernet/sing v0.2.7` 记得删除旧版本 xray-core main 已经更新到0.2.7 版本 就不会报错了。
